name: release

on:
  push:
    tags:
      "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: docker://antonyurchenko/git-release:v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_EMPTY_CHANGELOG: "true"
        with:
          args: |
            Shell/Breakpoint.itermcolors
            Shell/Breakpoint.terminal
            Shell/Breakpoint.zsh-theme